spring:
    application:
        name: warehouse-service

    datasource:
        url: ${DB_URL:jdbc:postgresql://localhost:5432/warehouse-management}
        username: ${DB_USERNAME:postgres}
        password: ${DB_PASSWORD:venkat}
        driver-class-name: org.postgresql.Driver

    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                format_sql: true

    flyway:
        enabled: true

security:
    jwt:
        secret: ${JWT_SECRET:Y2hhbmdlLW1tLWluLXByb2QtMzJieXRlcy1taW4tISEh}
        issuer: ${JWT_ISSUER:warehouse-service}
        access-token-ttl: ${JWT_ACCESS_TTL:15m}
        refresh-token-ttl: ${JWT_REFRESH_TTL:7d}

server:
    port: ${SERVER_PORT:8081}

inbound:
    service:
        url: ${INBOUND_SERVICE_URL:http://localhost:8082}

management:
    endpoints:
        web:
            exposure:
                include: health,info,metrics
    endpoint:
        health:
            probes:
                enabled: true

springdoc:
    swagger-ui:
        path: /swagger-ui.html